services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Slub\SlubProfileAccount\:
    resource: '../Classes/*'

  Slub\SlubProfileAccount\Http\Request:
    public: true

  Slub\SlubProfileAccount\Service\ApiService:
    public: true
